language: python


python:
  - '3.6'

services:
  - postgresql
  - redis-server

addons:
  apt:
    packages:
    - libenchant-dev

install:
  - pip install --upgrade setuptools
  - pip install -r requirements-dev.txt
  - pip install demos/polls
  - pip install demos/chat
  - pip install demos/blog
  - pip install demos/graphql

script:
  - make lint
  - make test
  - make doc-spelling
